development:
  adapter: postgresql
  encoding: unicode
  url: postgres://localhost:5432/nature_remo_log_development

production:
  adapter: mysql2
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
